# www.bastiankroggel.com
title: Bastian Kroggel
admin_user: Bastian Kroggel
author: Bastian Kroggel
email: contact@bastiankroggel.com
cr_date: 2015
description: > # this means to ignore newlines until "baseurl:"
  Bastian Kroggel | Graduated with a Corporate Management & Economics degree at <a href="https://www.zu.de" target="_blank">Zeppelin University</a> on the shores of Lake Constance and is currently working on tomorrows future at STARTUP AUTOBAHN powered by Plug and Play. Besides that a tech enthusiast interested in all things concerning great design, millennial and born digital native. Proud member of the CodeCats, an initiative attempting to excite pupils and students to enter the world of code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter: derkroggel
github:  bkroggel

# Pagination Settings
paginate: 4
paginate_path: "/:num/"

excerpt_separator: <!-- more -->
# Build settings
markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate, jekyll-feed]

sass:
  style: compressed

encoding: utf-8

#default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Bastian Kroggel"
      permalink: /blog/:year/:title/

compress_html:
  clippings: all
  comments: all
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
