backend:
  name: github
  repo: bkroggel/luzid # Path to your Github repository
  branch: master # Branch to update

media_folder: "assets/img/page/blog" # Media files will be stored in the repo under images/uploads

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Published"
        name: "published"
        widget: "boolean"
        default: "false"
        required: "false"
      - label: "Featured"
        name: "featured"
        widget: "boolean"
        default: "false"
        required: "false"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Sub-Title"
        name: "sub_title"
        widget: "string"
        required: "false"
      - label: "Date"
        name: "date"
        widget: "datetime"
        required: "false"
      - label: "Layout"
        name: "layout"
        widget: "string"
        default: "blog"
        required: "false"
      - label: "Author"
        name: "author"
        widget: "string"
        default: "Bastian Kroggel"
        required: "false"
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: "false"
      - label: "URL"
        name: "permalink"
        widget: "string"
        required: "false"
      - label: "Thumbnail"
        name: "thumbnail"
        widget: "object"
        required: "false"
        fields:
          - label: "Image"
            name: "img"
            widget: "image"
            required: "false"
          - label: "Overview"
            name: "overview"
            widget: "markdown"
            required: "false"
      - label: "Sitemap"
        name: "sitemap"
        widget: "object"
        required: "false"
        fields:
          - label: "Last Modified"
            name: "lastmod"
            widget: "datetime"
            required: "false"
          - label: "Priority"
            name: "priority"
            widget: "number"
            required: "false"
          - label: "Frequence of Change"
            name: "changefreq"
            widget: "select"
            default: "monthly"
            required: "false"
            options:
              - always
              - hourly
              - daily
              - weekly
              - monthly
              - yearly
              - never
          - label: "Exclude from Sitemap"
            name: "exclude"
            widget: "boolean"
            required: "false"
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: "false"
      - label: "Signed Post"
        name: "sign"
        widget: "boolean"
        default: "false"
        required: "false"

  - name: "sites"
    label: "Sites"
    files:
      - name: "about"
        label: "About"
        file: "about.md"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Header"
            name: "header"
            widget: "object"
            fields:
              - label: "Header-Image"
                name: "img"
                widget: "object"
                fields:
                  - {label: "URL", name: "url", widget: "string"}
                  - {label: "Image Title", name: "title", widget: "string"}
                  - {label: "Photographer", name: "photographer", widget: "string"}
              - {label: "Intro-Title", name: "title", widget: "text"}
              - {label: "Intro Sub-Title", name: "subtitle", widget: "string"}
          - label: "Quote"
            name: "quote"
            widget: "object"
            fields:
              - {label: "Text", name: "text", widget: "text"}
              - {label: "Qote Author", name: "author", widget: "string"}
          - label: "Body"
            name: "body"
            widget: "markdown"
            required: "false"
          - label: "Signed Page"
            name: "sign"
            widget: "boolean"
            required: "false"
          - label: "Timeline"
            name: "timeline"
            widget: "list"
            fields:
              - {label: "Company Name", name: "name", widget: "string"}
              - {label: "Position", name: "position", widget: "string"}
              - {label: "Start Date", name: "from_date", widget: "date", format:"MM/YYYY"}
              - {label: "End Date", name: "to_date", widget: "date", format:"MM/YYYY"}
              - {label: "Company Info", name: "info", widget: "text"}
              - {label: "Description", name: "description", widget: "markdown"}
              - {label: "Website", name: "website", widget: "string", pattern: ['_^(?:(?:https?|ftp)://)(?:\S+(?::\S*)?@)?(?:(?!10(?:\.\d{1,3}){3})(?!127(?:\.\d{1,3}){3})(?!169\.254(?:\.\d{1,3}){2})(?!192\.168(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\x{00a1}-\x{ffff}0-9]+-?)*[a-z\x{00a1}-\x{ffff}0-9]+)(?:\.(?:[a-z\x{00a1}-\x{ffff}0-9]+-?)*[a-z\x{00a1}-\x{ffff}0-9]+)*(?:\.(?:[a-z\x{00a1}-\x{ffff}]{2,})))(?::\d{2,5})?(?:/[^\s]*)?$_iuS', "Must be a valid URL"]}
